openQrCode: true
loverPrattle:
  enable: true
  cron: 0 0 9 * * ?
  city: 广州
  nickName: 悦
  fallInLoveAt: 2014-02-15
  sweetsWords: 来自养猪场的程序猿

autoReply:
  enable: true
  tulingApiKey: b24b376ec0444b418035720785a8cde4
  nickNames:
    - Bot567
  prefix: 【~(≧▽≦)~】