openQrCode: true
loverPrattle:
  enable: true
  cron: 0/30 * * * * ?
  city: 广州
  nickName: 東
  fallInLoveAt: 2014-02-15
  sweetsWords: 来自养猪场的程序猿

autoReply:
  enable: true
  nickNames:
    - Bot群456
  prefix: 【~(≧▽≦)~】